// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"github.com/mbilarusdev/durak_auth_bot/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCodeProvider creates a new instance of MockCodeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodeProvider {
	mock := &MockCodeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodeProvider is an autogenerated mock type for the CodeProvider type
type MockCodeProvider struct {
	mock.Mock
}

type MockCodeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodeProvider) EXPECT() *MockCodeProvider_Expecter {
	return &MockCodeProvider_Expecter{mock: &_m.Mock}
}

// DelCode provides a mock function for the type MockCodeProvider
func (_mock *MockCodeProvider) DelCode(phoneNumber string) error {
	ret := _mock.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for DelCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(phoneNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCodeProvider_DelCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelCode'
type MockCodeProvider_DelCode_Call struct {
	*mock.Call
}

// DelCode is a helper method to define mock.On call
//   - phoneNumber string
func (_e *MockCodeProvider_Expecter) DelCode(phoneNumber interface{}) *MockCodeProvider_DelCode_Call {
	return &MockCodeProvider_DelCode_Call{Call: _e.mock.On("DelCode", phoneNumber)}
}

func (_c *MockCodeProvider_DelCode_Call) Run(run func(phoneNumber string)) *MockCodeProvider_DelCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodeProvider_DelCode_Call) Return(err error) *MockCodeProvider_DelCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCodeProvider_DelCode_Call) RunAndReturn(run func(phoneNumber string) error) *MockCodeProvider_DelCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetCode provides a mock function for the type MockCodeProvider
func (_mock *MockCodeProvider) GetCode(phoneNumber string) (string, error) {
	ret := _mock.Called(phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetCode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(phoneNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(phoneNumber)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(phoneNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCodeProvider_GetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCode'
type MockCodeProvider_GetCode_Call struct {
	*mock.Call
}

// GetCode is a helper method to define mock.On call
//   - phoneNumber string
func (_e *MockCodeProvider_Expecter) GetCode(phoneNumber interface{}) *MockCodeProvider_GetCode_Call {
	return &MockCodeProvider_GetCode_Call{Call: _e.mock.On("GetCode", phoneNumber)}
}

func (_c *MockCodeProvider_GetCode_Call) Run(run func(phoneNumber string)) *MockCodeProvider_GetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodeProvider_GetCode_Call) Return(s string, err error) *MockCodeProvider_GetCode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCodeProvider_GetCode_Call) RunAndReturn(run func(phoneNumber string) (string, error)) *MockCodeProvider_GetCode_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCode provides a mock function for the type MockCodeProvider
func (_mock *MockCodeProvider) SaveCode(phoneNumber string, code string) error {
	ret := _mock.Called(phoneNumber, code)

	if len(ret) == 0 {
		panic("no return value specified for SaveCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(phoneNumber, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCodeProvider_SaveCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCode'
type MockCodeProvider_SaveCode_Call struct {
	*mock.Call
}

// SaveCode is a helper method to define mock.On call
//   - phoneNumber string
//   - code string
func (_e *MockCodeProvider_Expecter) SaveCode(phoneNumber interface{}, code interface{}) *MockCodeProvider_SaveCode_Call {
	return &MockCodeProvider_SaveCode_Call{Call: _e.mock.On("SaveCode", phoneNumber, code)}
}

func (_c *MockCodeProvider_SaveCode_Call) Run(run func(phoneNumber string, code string)) *MockCodeProvider_SaveCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCodeProvider_SaveCode_Call) Return(err error) *MockCodeProvider_SaveCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCodeProvider_SaveCode_Call) RunAndReturn(run func(phoneNumber string, code string) error) *MockCodeProvider_SaveCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayerProvider creates a new instance of MockPlayerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerProvider {
	mock := &MockPlayerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayerProvider is an autogenerated mock type for the PlayerProvider type
type MockPlayerProvider struct {
	mock.Mock
}

type MockPlayerProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerProvider) EXPECT() *MockPlayerProvider_Expecter {
	return &MockPlayerProvider_Expecter{mock: &_m.Mock}
}

// FindOne provides a mock function for the type MockPlayerProvider
func (_mock *MockPlayerProvider) FindOne(options *models.PlayerFindOptions) (*models.Player, error) {
	ret := _mock.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *models.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.PlayerFindOptions) (*models.Player, error)); ok {
		return returnFunc(options)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.PlayerFindOptions) *models.Player); ok {
		r0 = returnFunc(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.PlayerFindOptions) error); ok {
		r1 = returnFunc(options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerProvider_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockPlayerProvider_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - options *models.PlayerFindOptions
func (_e *MockPlayerProvider_Expecter) FindOne(options interface{}) *MockPlayerProvider_FindOne_Call {
	return &MockPlayerProvider_FindOne_Call{Call: _e.mock.On("FindOne", options)}
}

func (_c *MockPlayerProvider_FindOne_Call) Run(run func(options *models.PlayerFindOptions)) *MockPlayerProvider_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.PlayerFindOptions
		if args[0] != nil {
			arg0 = args[0].(*models.PlayerFindOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayerProvider_FindOne_Call) Return(player *models.Player, err error) *MockPlayerProvider_FindOne_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *MockPlayerProvider_FindOne_Call) RunAndReturn(run func(options *models.PlayerFindOptions) (*models.Player, error)) *MockPlayerProvider_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockPlayerProvider
func (_mock *MockPlayerProvider) Insert(player *models.Player) (uint64, error) {
	ret := _mock.Called(player)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Player) (uint64, error)); ok {
		return returnFunc(player)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Player) uint64); ok {
		r0 = returnFunc(player)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Player) error); ok {
		r1 = returnFunc(player)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerProvider_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockPlayerProvider_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - player *models.Player
func (_e *MockPlayerProvider_Expecter) Insert(player interface{}) *MockPlayerProvider_Insert_Call {
	return &MockPlayerProvider_Insert_Call{Call: _e.mock.On("Insert", player)}
}

func (_c *MockPlayerProvider_Insert_Call) Run(run func(player *models.Player)) *MockPlayerProvider_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Player
		if args[0] != nil {
			arg0 = args[0].(*models.Player)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayerProvider_Insert_Call) Return(v uint64, err error) *MockPlayerProvider_Insert_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockPlayerProvider_Insert_Call) RunAndReturn(run func(player *models.Player) (uint64, error)) *MockPlayerProvider_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenProvider creates a new instance of MockTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenProvider {
	mock := &MockTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenProvider is an autogenerated mock type for the TokenProvider type
type MockTokenProvider struct {
	mock.Mock
}

type MockTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenProvider) EXPECT() *MockTokenProvider_Expecter {
	return &MockTokenProvider_Expecter{mock: &_m.Mock}
}

// FindOne provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) FindOne(options *models.TokenFindOptions) (*models.Token, error) {
	ret := _mock.Called(options)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *models.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.TokenFindOptions) (*models.Token, error)); ok {
		return returnFunc(options)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.TokenFindOptions) *models.Token); ok {
		r0 = returnFunc(options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.TokenFindOptions) error); ok {
		r1 = returnFunc(options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockTokenProvider_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - options *models.TokenFindOptions
func (_e *MockTokenProvider_Expecter) FindOne(options interface{}) *MockTokenProvider_FindOne_Call {
	return &MockTokenProvider_FindOne_Call{Call: _e.mock.On("FindOne", options)}
}

func (_c *MockTokenProvider_FindOne_Call) Run(run func(options *models.TokenFindOptions)) *MockTokenProvider_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.TokenFindOptions
		if args[0] != nil {
			arg0 = args[0].(*models.TokenFindOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_FindOne_Call) Return(token *models.Token, err error) *MockTokenProvider_FindOne_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenProvider_FindOne_Call) RunAndReturn(run func(options *models.TokenFindOptions) (*models.Token, error)) *MockTokenProvider_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) Insert(token *models.Token) (uint64, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.Token) (uint64, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Token) uint64); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Token) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenProvider_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTokenProvider_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - token *models.Token
func (_e *MockTokenProvider_Expecter) Insert(token interface{}) *MockTokenProvider_Insert_Call {
	return &MockTokenProvider_Insert_Call{Call: _e.mock.On("Insert", token)}
}

func (_c *MockTokenProvider_Insert_Call) Run(run func(token *models.Token)) *MockTokenProvider_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Token
		if args[0] != nil {
			arg0 = args[0].(*models.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenProvider_Insert_Call) Return(v uint64, err error) *MockTokenProvider_Insert_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTokenProvider_Insert_Call) RunAndReturn(run func(token *models.Token) (uint64, error)) *MockTokenProvider_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTokenProvider
func (_mock *MockTokenProvider) UpdateStatus(ID uint64, status string) error {
	ret := _mock.Called(ID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) error); ok {
		r0 = returnFunc(ID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenProvider_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTokenProvider_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ID uint64
//   - status string
func (_e *MockTokenProvider_Expecter) UpdateStatus(ID interface{}, status interface{}) *MockTokenProvider_UpdateStatus_Call {
	return &MockTokenProvider_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ID, status)}
}

func (_c *MockTokenProvider_UpdateStatus_Call) Run(run func(ID uint64, status string)) *MockTokenProvider_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenProvider_UpdateStatus_Call) Return(err error) *MockTokenProvider_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenProvider_UpdateStatus_Call) RunAndReturn(run func(ID uint64, status string) error) *MockTokenProvider_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
