package repository_test

import (
	"fmt"
	"testing"

	"context"
	"time"

	"github.com/docker/go-connections/nat"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/mbilarusdev/durak_auth_bot/internal/adapter"
	"github.com/mbilarusdev/durak_auth_bot/internal/repository"
	app_model "github.com/mbilarusdev/durak_auth_bot/internal/structs/app/model"
	app_option "github.com/mbilarusdev/durak_auth_bot/internal/structs/app/option"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func TestPlayerRepositoryDocker(t *testing.T) {
	ctx := context.Background()
	req := testcontainers.ContainerRequest{
		Image:        "postgres:latest",
		ExposedPorts: []string{"5432/tcp"},
		WaitingFor:   wait.ForListeningPort(nat.Port("5432/tcp")),
		Env: map[string]string{
			"POSTGRES_USER":     "test_user",
			"POSTGRES_PASSWORD": "test_password",
			"POSTGRES_DB":       "test_db",
		},
	}
	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		t.Fatalf("Couldn't start container: %s", err)
	}
	defer container.Terminate(ctx)

	ip, err := container.Host(ctx)
	if err != nil {
		t.Fatalf("Couldn't get host ip: %s", err)
	}

	port, err := container.MappedPort(ctx, "5432")
	if err != nil {
		t.Fatalf("Couldn't get mapped port: %s", err)
	}

	dsn := fmt.Sprintf(
		"postgres://test_user:test_password@%s:%s/test_db?sslmode=disable&pool_max_conns=1&pool_max_conn_lifetime=1h30m",
		ip,
		port.Port(),
	)

	time.Sleep(time.Second * 5)

	conf, err := pgxpool.ParseConfig(dsn)

	if err != nil {
		t.Fatalf("Error when parse config: %s", err)
	}

	pool, err := pgxpool.NewWithConfig(ctx, conf)
	if err != nil {
		t.Fatalf("Failed to create pgx pool: %s", err)
	}
	defer pool.Close()

	conn, err := pool.Acquire(ctx)
	if err != nil {
		t.Fatalf("Failed to get pgx conn from pool: %s", err)
	}

	_, err = conn.Exec(ctx, `
        CREATE TABLE IF NOT EXISTS players (
		id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		username    VARCHAR(255) NOT NULL,
		phone_number VARCHAR(255) NOT NULL,
		chat_id     INTEGER NOT NULL,
		created_at  BIGINT NOT NULL
	);
    `)

	if err != nil {
		t.Fatalf("Couldn't create table: %s", err)
	}
	conn.Release()

	t.Run("All methods success", func(t *testing.T) {
		repository := repository.NewPlayerRepository(adapter.NewAdapterPool(pool))

		player := &app_model.Player{
			Username:    "Boris",
			PhoneNumber: "+79150321628",
			ChatID:      10,
			CreatedAt:   time.Now().UTC().Unix(),
		}
		playerID, err := repository.Insert(player)
		if err != nil {
			t.Fatalf("Create player failed: %s", err)
		}

		foundPlayerById, err := repository.FindOne(&app_option.PlayerFindOptions{ID: playerID})
		if err != nil {
			t.Fatalf("Get user by id failed: %s", err)
		}

		foundPlayerById.ID = 0
		if *foundPlayerById != *player {
			t.Fatalf("Test failed!")
		}

		conn, err := pool.Acquire(ctx)
		if err != nil {
			t.Fatalf("Failed to get pgx conn from pool: %s", err)
		}
		defer conn.Release()

		_, err = conn.Exec(ctx, "DELETE FROM players WHERE id = 1")

		if err != nil {
			t.Logf("Cleanup failed: %s", err)
		}
	})
}
